language: c
sudo: required
compiler:
  - gcc
os: linux
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y dpkg-dev debhelper dkms lintian sparse
- sudo apt-get install linux-headers-`uname -r`
script:
- make C=1 W=1 KCFLAGS=-Werror
# Testing dkms install/uninstall
- sudo make dkms_install
- sudo make dkms_uninstall
# Testing Debian package installation, configuration, and uninstall
- dpkg-buildpackage -b -uc
# Checks Debian packages for common inconsistencies and errors
- lintian -i -I --profile debian --show-overrides ../digimend-dkms_*.changes
- sudo apt-get install -y ../digimend-dkms_*_all.deb
- sudo apt-get remove -y digimend-dkms
- make dist
- sudo make install
- sudo make uninstall
